#This describes the different sections of the project

version: '3.8'

services:

  frontend:
    build: ./frontend
    hostname: frontend
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"

  backend:
   build: ./backend
   hostname: backend
   container_name: backend
   stdin_open: true
   ports:
      - "8080:8080"
   environment:
      - MONGO_URL=mongodb://mongodb:27017
   depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27000:27017
    volumes:
      - mongodb_volume:/data/db

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    profiles: ["init"]

volumes:
  mongodb_volume: