#This describes the different sections of the project

version: '3.8'

services:

  frontend:
    build: ./frontend
    hostname: frontend
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"

  #backend:
  #  build: ./backend
  #  hostname: backend
  #  container_name: backend

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27000:27017

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    profiles: ["init"]